# Generated by Django 3.0.4 on 2020-03-24 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('height', models.SmallIntegerField(default=64, verbose_name='Height (in.)')),
                ('weight', models.SmallIntegerField(default=150, verbose_name='Weight (lbs.)')),
                ('gender', models.CharField(choices=[('ML', 'Male'), ('FM', 'Female')], max_length=2)),
                ('myfitpal_user', models.CharField(max_length=50)),
                ('myfitpal_pw', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('calories', models.SmallIntegerField(default=0)),
                ('sodium', models.SmallIntegerField(default=0)),
                ('carbs', models.SmallIntegerField(default=0)),
                ('fat', models.SmallIntegerField(default=0)),
                ('sugar', models.SmallIntegerField(default=0)),
                ('protein', models.SmallIntegerField(default=0)),
                ('userid', models.CharField(max_length=50)),
                ('user_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydata.User')),
            ],
        ),
    ]
