# Generated by Django 3.0.4 on 2020-03-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calories', models.SmallIntegerField(default=0)),
                ('sodium', models.SmallIntegerField(default=0)),
                ('carbs', models.SmallIntegerField(default=0)),
                ('fat', models.SmallIntegerField(default=0)),
                ('sugar', models.SmallIntegerField(default=0)),
                ('protein', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
