# Generated by Django 3.0.4 on 2020-03-31 21:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('weight', models.SmallIntegerField(default=150, verbose_name='Weight (lbs.)')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('height', models.SmallIntegerField(default=64, verbose_name='Height (in.)')),
                ('birthday', models.DateField(default=datetime.date(1981, 9, 20), verbose_name='Birthday')),
                ('gender', models.CharField(choices=[('ML', 'Male'), ('FM', 'Female')], max_length=2)),
                ('start_date', models.DateField(default=datetime.date(2020, 3, 10), verbose_name='My Fitness Pal Start Date')),
                ('myfitpal_user', models.CharField(max_length=50)),
                ('myfitpal_pw', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.SmallIntegerField(default=0)),
                ('sodium', models.SmallIntegerField(default=0)),
                ('carbs', models.SmallIntegerField(default=0)),
                ('fat', models.SmallIntegerField(default=0)),
                ('sugar', models.SmallIntegerField(default=0)),
                ('protein', models.SmallIntegerField(default=0)),
                ('balance', models.SmallIntegerField(default=0)),
                ('date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mydata.Day')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='mydata.User')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydata.User'),
        ),
    ]
