# Generated by Django 3.0.4 on 2020-03-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrient',
            name='id',
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
