# Generated by Django 3.0.4 on 2020-03-25 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0002_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrient',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='nutrient',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='nutrient',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='nutrient',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='nutrient',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='nutrient',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='nutrient',
            name='userid',
        ),
    ]
