# Generated by Django 3.0.4 on 2020-03-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0002_auto_20200317_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrient',
            name='user',
            field=models.CharField(default='blafving@gmail.com', max_length=50),
        ),
    ]
