# Generated by Django 3.0.4 on 2020-03-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0003_auto_20200324_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrient',
            name='balance',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='calories',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='carbs',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='fat',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='protein',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='sodium',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='sugar',
            field=models.SmallIntegerField(default=0),
        ),
    ]
