# Generated by Django 3.0.4 on 2020-04-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0003_auto_20200331_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='weight',
        ),
        migrations.AddField(
            model_name='day',
            name='new_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight Reading (lbs.)'),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_init',
            field=models.DecimalField(decimal_places=2, default=195.1, max_digits=5, verbose_name='Weight'),
            preserve_default=False,
        ),
    ]
