# Generated by Django 3.0.4 on 2020-04-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0004_auto_20200331_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='new_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight Reading (lbs.)'),
        ),
    ]
