# Generated by Django 3.0.4 on 2020-04-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0005_auto_20200331_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='weight_init',
            field=models.FloatField(verbose_name='Weight'),
        ),
    ]
