# Generated by Django 3.0.4 on 2020-04-01 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0006_auto_20200331_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='user_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydata.User'),
        ),
    ]
