# Generated by Django 3.0.4 on 2020-04-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0007_auto_20200401_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrient',
            name='cal_burned',
            field=models.SmallIntegerField(default=0),
        ),
    ]
